language: python

notifications:
  recipients:
    - lasse.schuirmann@gmail.com
    - fabian@neuschmidt.de
  email:
    on_failure: always
    on_success: change

python:
  - "3.2"
  - "3.3"
  - "3.4"

script:
  - python setup.py test

