site_name: coala documentation
pages:
- Home: 'index.md'
- For Users:
    - 'Installation': 'Users/Install.md'
    - 'Tutorial': 'Users/Tutorial.md'
    - 'Writing Bears': 'Users/Writing_Bears.md'
    - 'coafile Specification': 'Users/coafile.md'
    - 'Glob Patterns': 'Users/Glob_Patterns.md'
    - 'Exit Codes': 'Users/Exit_Codes.md'
- Getting Involved:
    - 'Introduction': 'Getting_Involved/README.md'
    - 'Review': 'Getting_Involved/Review.md'
    - 'Codestyle': 'Getting_Involved/Codestyle.md'
    - 'Executing Tests': 'Getting_Involved/Testing.md'
    - 'Writing Tests': 'Getting_Involved/Writing_Tests.md'
    - 'Writing Documentation': 'Getting_Involved/Writing_Documentation.md'
    - 'Translating': 'Getting_Involved/Translating.md'
    - 'Writing Good Commits': 'Getting_Involved/Writing_Good_Commits.md'
    - 'MAC Hints': 'Getting_Involved/MAC_Hints.md'
- General Developer Information:
    - 'A Hitchhikers Guide To Git (1): Genesis': 'General_Dev_Info/git_tutorial_1.md'
theme: readthedocs
